### ISSUE TITLE
Feature: Support AutoClosing, Autosurrounding, and Folding

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeploy/vscode-octopusdeploy#12]
Currently, the grammar for OCL doesn't have configuration for [AutoClosing](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#autoclosing), [Autosurrounding](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#autosurrounding), and [Folding](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#folding). These should be added to provide a better editing experience.

**Comment by domenicsim1** [comment]
Merged feature: https://github.com/OctopusDeploy/vscode-octopusdeploy/commit/8dc9f9177aab07252a4e6a2e119ab5faa2276845
