### ISSUE TITLE
Bug: Syntax Highlighting Quirk When OCL Contains Variable-Expressions

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeploy/vscode-octopusdeploy#16]
![image](https://user-images.githubusercontent.com/71493/137389403-2566e33d-b0da-4585-bfc3-0f6bc181b9c4.png)

**Comment by domenicsim1** [comment]
Fixed in the following commit: https://github.com/OctopusDeploy/vscode-octopusdeploy/commit/a9da5108e06daee54e17cfe6c596f991c9e7561e
